# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

script:
  - R CMD INSTALL .
  - R -e "recipes::write_site()"

before_cache:
- nvm install stable
- npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy --prod --dir _book
  skip_cleanup: true
